### ISSUE TITLE
Failed to activate etheratom on OSX because regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by sproxet** [0mkara/etheratom#121] opened 2018-07-01 01:34 UTC
The error occurs as soon as a .sol file is opened, immediately after installation.

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [etheratom](https://github.com/0mkara/etheratom) package 4.3.5

### Stack Trace

Failed to activate the etheratom package

```
At regeneratorRuntime is not defined

ReferenceError: regeneratorRuntime is not defined
    at /packages/etheratom/build/main.js:353:46
    at /packages/etheratom/build/main.js:398:4
    at /packages/etheratom/build/main.js:1140:2)
    at /packages/etheratom/build/main.js:5096:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:650:18)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
atom-typescript 12.6.2 
etheratom 4.3.5 
file-icons 2.1.21 
ide-rust 0.17.1 
language-rust 0.4.12 
minimap 4.29.8 
project-manager 3.3.6 
```

**Comment by mrdavey** [comment] 2018-07-02 18:23
I'm having the same issues

**Comment by dv29** [comment] 2018-07-03 00:57
Having the same issue

**Comment by 0mkara** [comment] 2018-07-03 18:44
I was unable to reproduce this issue. Please try removing etheratom and then installing it again with command line `apm install etheratom`.

**Comment by sproxet** [comment] 2018-07-04 11:45
@0mkara I tried that before filing the issue (and again after your suggestion), but no luck.

**Comment by mrdavey** [comment] 2018-07-05 05:05
@0mkara same as the above comment

**Comment by 0mkara** [comment] 2018-07-05 09:44
@mrdavey @sproxet @dv29 I just published a patch. Now the `regeneratorRuntime` issue should be fixed.
Thanks for reporting the issue.

Please join [t.me/etheratom](https://t.me/etheratom) and support etheratom.

**Closed** 2018-07-10 09:53 UTC
